:syntax on
:set encoding=utf-8
:set background=dark
:set hlsearch
:set tabstop=4
:set shiftwidth=4
:set list
:set paste
:set visualbell
:set lcs=tab:¬…
:syntax on
:set expandtab

:set regexpengine=0
:syntax on
:filetype plugin indent on


:filetype plugin on
" type help zip
:au BufReadCmd *.whl call zip#Browse(expand("<amatch>"))
:au BufReadCmd *.pyz call zip#Browse(expand("<amatch>"))
